"use client";

import { motion } from "framer-motion";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AlertTriangle, Shield, Calendar, ExternalLink, TrendingUp, Lock, Globe, Smartphone } from "lucide-react";

const alerts = [
  { day: "Today", items: [
    { title: "New QR code phishing campaign targets parking meters", severity: "critical", category: "QR Phishing" },
    { title: "AI voice scam alerts: 300% increase in deepfake calls", severity: "high", category: "Voice Scam" },
    { title: "Fake banking apps on App Store steal credentials", severity: "critical", category: "Mobile" },
  ]},
  { day: "Yesterday", items: [
    { title: "WhatsApp 'free data' scam spreading rapidly in Asia", severity: "high", category: "Social Media" },
    { title: "New typosquatting domains targeting crypto exchanges", severity: "medium", category: "Crypto" },
  ]},
  { day: "This Week", items: [
    { title: "Phishing campaign impersonating IRS tax refunds", severity: "critical", category: "Tax Scam" },
    { title: "Fake LinkedIn premium offers lead to credential theft", severity: "high", category: "Job Scam" },
    { title: "Telegram scam groups offering fake trading signals", severity: "medium", category: "Crypto" },
    { title: "SMS spoofing attacks targeting major US banks", severity: "high", category: "Banking" },
  ]},
];

const recommendations = [
  { icon: Lock, title: "Enable 2FA", desc: "Two-factor authentication blocks 99.9% of account takeovers." },
  { icon: Shield, title: "Update Software", desc: "Latest patches fix security vulnerabilities." },
  { icon: Globe, title: "Verify URLs", desc: "Always check the real destination before clicking." },
  { icon: Smartphone, title: "Review Permissions", desc: "Check which apps have access to your data." },
];

export function CyberAlerts() {
  return (
    <section className="border-y border-border/40 bg-card/20 py-20">
      <div className="mx-auto max-w-6xl px-6">
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12 text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-amber-500/30 bg-amber-500/10 px-4 py-1.5 text-xs text-amber-300">
            <AlertTriangle className="h-3.5 w-3.5" /> Daily cyber intelligence
          </div>
          <h2 className="text-3xl font-bold md:text-4xl">AI-Generated Cyber Alerts</h2>
          <p className="mx-auto mt-4 max-w-xl text-muted-foreground">
            Daily threat briefings generated by our AI from global security feeds
          </p>
        </motion.div>

        <div className="grid gap-8 lg:grid-cols-3">
          <div className="lg:col-span-2 space-y-6">
            {alerts.map((group) => (
              <div key={group.day}>
                <div className="flex items-center gap-2 mb-3">
                  <Calendar className="h-4 w-4 text-cyan-400" />
                  <h3 className="text-sm font-semibold">{group.day}</h3>
                </div>
                <div className="space-y-2">
                  {group.items.map((alert, i) => (
                    <motion.div
                      key={alert.title}
                      initial={{ opacity: 0, x: -10 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: i * 0.05 }}
                      className="flex items-start gap-3 rounded-lg border border-border/50 bg-card/30 p-3 transition hover:border-cyan-500/20"
                    >
                      <div className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-lg ${
                        alert.severity === "critical" ? "bg-rose-500/20" : alert.severity === "high" ? "bg-amber-500/20" : "bg-cyan-500/10"
                      }`}>
                        <AlertTriangle className={`h-3.5 w-3.5 ${
                          alert.severity === "critical" ? "text-rose-400" : alert.severity === "high" ? "text-amber-400" : "text-cyan-400"
                        }`} />
                      </div>
                      <div className="min-w-0 flex-1">
                        <p className="text-sm">{alert.title}</p>
                        <div className="flex items-center gap-2 mt-1">
                          <Badge variant={alert.severity as "critical" | "high" | "medium" | "low"} className="text-[9px]">{alert.severity}</Badge>
                          <span className="text-[10px] text-muted-foreground">{alert.category}</span>
                        </div>
                      </div>
                      <button className="shrink-0 text-muted-foreground hover:text-cyan-400 transition">
                        <ExternalLink className="h-3.5 w-3.5" />
                      </button>
                    </motion.div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="space-y-4">
            <Card className="glass">
              <CardContent className="p-5">
                <div className="flex items-center gap-2 mb-4">
                  <TrendingUp className="h-4 w-4 text-cyan-400" />
                  <h3 className="text-sm font-semibold">AI Safety Recommendations</h3>
                </div>
                <div className="space-y-4">
                  {recommendations.map((r) => (
                    <div key={r.title} className="flex gap-3">
                      <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-cyan-500/10">
                        <r.icon className="h-4 w-4 text-cyan-400" />
                      </div>
                      <div>
                        <p className="text-sm font-medium">{r.title}</p>
                        <p className="text-xs text-muted-foreground">{r.desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            <Card className="glass border-amber-500/20">
              <CardContent className="p-5 text-center">
                <AlertTriangle className="mx-auto h-8 w-8 text-amber-400" />
                <p className="mt-3 text-sm font-medium">Weekly Threat Report</p>
                <p className="mt-1 text-xs text-muted-foreground">
                  1,247 new threats detected this week. Stay informed with our AI-curated security digest.
                </p>
                <Badge variant="outline" className="mt-3 border-amber-500/30 text-amber-400">
                  Updated 2h ago
                </Badge>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </section>
  );
}
